[theme]

# Base colors can be 'light' or 'dark'
base = "light"

# Primary color for your app, specified as a hex or named CSS color
primaryColor = "#dc4c87"

# Background color for your app
backgroundColor = "#f2f2f0"

# Secondary background color for your app
secondaryBackgroundColor = "#dcdcdd"

# Text color for your app
textColor = "#334155"

# Font for your app, choose between "sans serif", "serif", and "monospace"
font = "sans serif"
